export const ADD_GRAVATAR = 'ADD_GRAVATAR';

export const ACTIVE_LOGIN = 'ACTIVE_LOGIN';

export const ADD_NEW_QUESTIONS = 'ADD_NEW_QUESTIONS';

export const QUESTION_REQUEST = 'QUESTION_REQUEST';

export const ADD_SCORE = 'ADD_SCORE';

export const DECREASE_TIME = 'DECREASE_TIME';

export const RESET_TIMER_QUESTION = 'RESET_TIMER_QUESTION';

export const DISABLE_BUTTON = 'DISABLE_BUTTON';

export const SHOW_BUTTON = 'SHOW_BUTTON';

export const RESET_FUNCTIONS = 'RESET_FUNCTIONS';

export const ADD_OPTION_ANSWERS = 'ADD_OPTION_ANSWERS';

export const CLEAN_OPTION_ANSWERS = 'CLEAN_OPTION_ANSWERS';

export const ADD_ASSERTIONS = 'ADD_ASSERTIONS';

export const RESET_QUESTIONS = 'RESET_QUESTIONS';

export const NEW_GAME = 'NEW_GAME';

export const CLEAR_QUESTIONS = 'CLEAR_QUESTIONS';

export const CLEAR_OPTION_ANSWERS = 'CLEAR_OPTION_ANSWERS';

export const RESET_PLAYER = 'RESET_PLAYER';

export const SET_CLASS_REDUCER = 'SET_CLASS_REDUCER';

export const CLEAR_CLASS_REDUCER = 'CLEAR_CLASS_REDUCER';
